version: '3.8'

services:

#  proxy:
#    image: nginx:stable-alpine
#    ports:
#      - 80:80
#    networks:
#      - frontend
#      - backend
#    volumes:
#      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - frontend
#      - backend

  frontend:
    image: realworld_frontend:${TAG:-latest}
    ports:
      - 3000:80
    networks:
      - frontend

  backend:
    image: realworld_backend:${TAG:-latest}
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - backend
      - mysql-network
      

networks: 
  frontend:
  backend:
  mysql-network:
    external: true
