version: '3.8'

services:

  frontend:
    image: realworld_frontend:${TAG:-latest}-local
    build:
      context: ./frontend
      target: build-stage
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:80"
    environment: 
      - PORT=80
    command:
      - sh 
      - -c 
      - yarn serve --disable-host-check

  backend:
    image: realworld_backend:${TAG:-latest}-local
    build:
      context: ./backend
      target: build-stage
    volumes:
      - ./backend:/home/gradle/project
      - /home/gradle/project/.gradle
      - /home/gradle/project/build
    environment: 
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - 8080:8080
    command:
      - sh
      - -c
      - ./gradlew bootRun
